# Generated by Django 5.0.3 on 2024-03-07 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cid', models.IntegerField()),
                ('P_Date', models.DateTimeField()),
                ('Category', models.CharField(max_length=64)),
                ('Price', models.FloatField()),
                ('Quantity', models.IntegerField()),
                ('TPAmt', models.FloatField()),
                ('Payment', models.CharField(max_length=64)),
                ('Returns', models.FloatField()),
                ('Name', models.CharField(max_length=128)),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(max_length=8)),
                ('Churn', models.IntegerField()),
            ],
        ),
    ]
